### ISSUE TITLE
Analyze Chainlink

### ISSUE THREAD

**Issue by pragalli** [BootNodeDev/nexus-smart-contracts#23]

**Comment by pragalli** [comment]
Definition of Done:
 - Estimate effort to implement Chainlink

**Comment by patitonar** [comment]
Docs: https://docs.chain.link/docs/consuming-data-feeds/
Feeds: https://data.chain.link/
Lido (stETH) oracle feeds: https://docs.lido.fi/deployed-contracts#price-feeds
Aave integration example: https://github.com/aave/aave-v3-core/blob/master/contracts/misc/AaveOracle.sol
Example of using oracle to check slippage tolerance: https://github.com/aave/aave-v3-periphery/blob/212336107006cbe247f5ee6dea7cb08f5fc34b6f/contracts/adapters/paraswap/BaseParaSwapBuyAdapter.sol#L55-L68

**Comment by patitonar** [comment]
Chainlink Suppport Analysis
---
## General comments
Use PriceFeedOracle contract to get the price of the assets in CowSwapOperator.
Use ETH as the base currency for the price feed.

Chainlink ETH pairs feeds: 18 Decimals
List of potential chainlink aggregators:
- DAI/ETH
- USDC/ETH
- BTC/ETH
- STETH/ETH (Not listed in Chainlink feeds official site only on Lido docs. Used by Aave)
- Other assets?

## Implementation tasks
1. Update PriceFeedOracle contract:
    - Update constructor to receive a list of aggregators
    - Remove hardcoded code for dai address and stETH in getAssetToEthRate() and getAssetForEth()
    - Add methods to add/remove aggregators only by governance
2. Update PriceFeedOracle deploy script to provide a list of aggregators
3. Add/update required tests
